name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup DotNet 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '3.1.x'

    - name: Setup DotNet 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install Tools
      run: |
        dotnet new tool-manifest
        dotnet tool install JetBrains.ReSharper.GlobalTools --tool-path dotnet-tools
        dotnet tool install nvika
        dotnet tool restore

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Run InspectCode
      run: dotnet-tools\jb inspectcode --build --swea --severity=SUGGESTION --output=inspectcode.xml JsonFeed.Net.sln

    - name: Run NVika
      run: dotnet nvika parsereport inspectcode.xml
