name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore Tools
      run: dotnet tool restore

    - name: Build Project
      run: dotnet build

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Run InspectCode
      run: dotnet jb inspectcode --no-build --swea --severity=SUGGESTION --output=inspectcode.xml *.sln

    - name: Run NVika
      run: dotnet nvika parsereport "inspectcode.xml"