name: Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup DotNet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.x

    - name: Restore Tools
      run: dotnet tool restore

    - name: Build Project
      run: dotnet build

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Run InspectCode
      run: dotnet jb inspectcode --no-build --swea --severity=SUGGESTION --format="xml" --output=inspectcode.xml *.sln

    - name: Run NVika
      run: dotnet nvika parsereport "inspectcode.xml"
